from enum import Enum


class ErrorType(Enum):
    # Lexer error
    INVALID_EXPONENTIAL_NUMBER = 'LEXICAL-ERROR-INVALID_EXPONENTIAL_NUMBER'
    INVALID_INTEGER_NUMBER = 'LEXICAL-ERROR-INVALID_INTEGER_NUMBER'
