from enum import Enum


class ErrorType(Enum):
    # Lexer error
    INVALID_EXPONENTIAL_NUMBER = 'LEXICAL-ERROR-INVALID_EXPONENTIAL_NUMBER'
    INVALID_INTEGER_NUMBER = 'LEXICAL-ERROR-INVALID_INTEGER_NUMBER'


class ErrorTypeSemantic(Enum):
    # Semantic error
    TYPE_MISMATCH = 'SEMANTIC-ERROR-TYPE-MISMATCH'
    UNDECLARED_VARIABLE = 'SEMANTIC-ERROR-UNDECLARED-VARIABLE'
    USAGE_OF_RESERVED_IDENTIFIER = 'SEMANTIC-ERROR-USAGE-OF-RESERVED-IDENTIFIER'
    MULTIPLE_VARIABLE_DECLARATION = 'SEMANTIC-ERROR-MULTIPLE-VARIABLE-DECLARATION'
